export type RoleCode =
  | "waiter"
  | "captain"
  | "cook"
  | "barman"
  | "chef_manager";

export const ROLE_OPTIONS: { value: RoleCode; label: string }[] = [
  { value: "waiter", label: "Mesero" },
  { value: "captain", label: "Capitán" },
  { value: "cook", label: "Cocinero" },
  { value: "barman", label: "Barman" },
  { value: "chef_manager", label: "Chef gerente" },
];

export const QUESTION_BANK: Record<
  RoleCode,
  { label: string; practical: string[]; psychometric: string[] }
> = {
  waiter: {
    label: "Mesero",
    practical: [
      "Explica paso a paso cuál debe ser la secuencia ideal de servicio desde que un cliente se sienta hasta que recibe la cuenta ( Incluye tiempos, lenguaje corporal y momentos clave.)",
      "Describe cómo se llena una comanda de acuerdo con el sistema tradicional en papel.",
      "Un cliente dice: “Mi platillo no está como lo pedí”. Explica paso a paso qué haces, qué dices y cómo decides si se repone, cambia o ajusta.",
      "Explica cómo recomendarías tres platillos y una bebida sin sonar insistente.",
      "Describe cómo recomendarías una bebida para acompañar: ● Chamorro ● Aguachile ● Carnitas ● Explica por qué cada bebida combina bien con cada platillo.",
      "“Llega a tu sección una mesa de 4 personas que sólo pide agua y no desea ordenar comida”. ¿Cómo actuarías para llevar esa mesa de bajo consumo a un ticket saludable evitando presión? Incluye:",
      "¿Cómo debe estar montada una mesa correcta antes de sentar al comensal? ¿Cómo verificas y corriges el montaje de tu equipo durante el servicio sin romper el ritmo de la sala?",
      "Tienes tres mesas que requieren atención al mismo tiempo, pero además debes supervisar a dos meseros nuevos en tu estación. Describe cómo decides prioridades, cómo distribuyes tareas y cómo mantienes calidad en toda tu zona.",
      "Explica cómo entregarías la cuenta profesionalmente, cómo auditas que el mesero la entregue correctamente y cómo previenes errores como dobles cobros o cuentas mal divididas.",
      "Un comensal se muestra impaciente o levanta la voz. Describe paso a paso cómo lo manejas manteniendo la calma, cuidando tu seguridad, la del equipo, y la experiencia del resto de los clientes.",
    ],
    psychometric: [
      "Cuéntame de la última vez que dos personas del equipo discutieron fuerte. ¿Qué hiciste tú para resolverlo?”",

      "Describe cómo manejas a alguien que constantemente genera problemas, chismes o mala actitud.”",

      "“Si cocina y piso están peleando por tiempos o errores, ¿qué haces para que vuelvan a trabajar como equipo?”",

      "¿Qué haces si ves que un conflicto está afectando el servicio en vivo?”",

      "“¿Cómo hablas con alguien que se pone a la defensiva cada vez que le das retroalimentación?”",
      "“Cuéntame de la situación más estresante que has vivido en el trabajo. ¿Qué pasó y cómo la manejaste tú personalmente?”",
      "“Cuando tienes muchos pendientes al mismo tiempo y todo urge, ¿cómo decides por dónde empezar?”",
      "“¿Qué haces cuando sientes que ya te estás saturando o poniendo de malas en medio del servicio?",
      "“Describe un día en el que todo salió mal (clientes, equipo, proveedores). ¿Cómo te organizaste para no perder el control?”",
      "“¿Qué haces para mantenerte enfocado cuando hay presión externa (dueño, clientes, fallas, etc.)?”",
      "“¿Qué opinas de tener estándares estrictos (tiempos, calidad, porciones)? ¿Te motivan o te frustran?”",
      "“Cuando tienes que repetir una tarea muchas veces (limpiar, revisar, ordenar) ¿cómo lo haces sin perder energía?”",
      "“¿Qué haces si un día estás cansado o de malas pero tienes que dar servicio de excelencia?”",
      "“¿Qué prefieres: libertad total o reglas claras? ¿Por qué?”",
      "“¿Qué harías si un compañero se está ‘haciendo menso’ y no trabaja al ritmo?”",
      "“¿Cómo reaccionas cuando te cambian el plan de último minuto?”",
      "“¿Qué haces cuando un superior te corrige enfrente de otros?”",
      "“¿Cómo describirías tu estilo de comunicación con clientes?”",
      "“¿Qué haces cuando un cliente te trata con poca educación?”",
      "“¿Cómo decides cuándo insistir en una venta y cuándo no?”",
      "“¿Qué tan cómodo te sientes recomendando productos más caros? ¿Por qué?”",
      "“¿Qué haces si cometes un error con una cuenta?”",
      "“¿Qué haces si un cliente dice que no pidió algo que aparece en la cuenta?”",
      "“¿Cómo te organizas mentalmente para atender 4–6 mesas al mismo tiempo?”",
      "“¿Te consideras rápido aprendiendo? Dame un ejemplo.”",
      "“¿Qué haces cuando no entiendes una instrucción?”",
      "“¿Cómo te gusta recibir feedback?”",
      "“¿Qué te molesta más en un equipo de trabajo?”",
      "“¿Qué valoras más: velocidad o perfección?”",
      "“¿Qué haces si un compañero nuevo comete errores que te afectan?”",
      "“¿Qué tan importante es para ti la puntualidad?”",
      "“¿Qué haces si llegas y ves que nadie ha montado tu estación?”",
      "“¿Qué te hace sentir orgulloso en un trabajo?”",
      "“¿Qué te haría renunciar a un trabajo?”",
      "“¿Cómo manejas el rechazo (cliente dice no)?”",
      "“¿Qué haces si estás en desacuerdo con una regla?”",
      "“¿Qué tan importante es para ti seguir procesos?”",
      "“¿Qué opinas de trabajar fines de semana y noches?”",
      "“¿Qué haces para mantener buena actitud cuando estás cansado?”",
      "“¿Qué haces si ves a alguien robando?”",
      "“¿Cómo reaccionas cuando te dan una tarea que no te gusta?”",
      "“¿Qué tan competitivo eres?”",
      "“¿Cómo te adaptas a cambios de menú?”",
      "“¿Qué haces si un cliente pide algo fuera de menú?”",
      "“¿Cómo manejas propinas y justicia entre equipo?”",
      "“¿Qué haces si alguien no comparte propinas correctamente?”",
      "“¿Qué haces para mantenerte en control cuando hay caos?”",
      "“¿Cómo manejas tu estrés fuera del trabajo?”",
      "“¿Qué haces si un cliente te graba o te insulta?”",
      "“¿Qué haces cuando el jefe te pide algo urgente?”",
      "“¿Qué haces cuando hay ruido y presión?”",
      "“¿Qué harías si te ofrecen un atajo (no seguir proceso)?”",
    ],
  },
  captain: {
    label: "Capitán",
    practical: [
      "Describe tu checklist ideal de apertura para un turno de comedor/terraza (incluye mesas, personal, montaje, insumos, música y clima).",
      "Explica paso a paso cómo asignas secciones, rotación y prioridades a tu equipo al inicio del turno.",
      "Un mesero te reporta que un cliente está molesto por un error del kitchen/pase. ¿Cómo intervienes y qué decides?",
      "Explica cómo haces un recorrido de sala (floor check) y qué indicadores observas para detectar fallas antes de que escalen.",
      "Describe cómo manejarías una noche con alta demanda y falta de personal (2 meseros menos). ¿Qué ajustes haces?",
      "¿Cómo entrenas en vivo a un mesero nuevo sin bajar calidad de servicio? Da un ejemplo concreto.",
      "Explica cómo manejarías una queja fuerte con posible compensación (descuento/cortesía). ¿Qué criterios usas?",
      "¿Cómo coordinas con cocina/bar cuando hay demoras? ¿Qué dices al cliente y qué haces internamente?",
      "Describe cómo auditas cuentas, pagos, cortesías y previenes errores (dobles cobros, cuentas mal divididas, tickets perdidos).",
      "Un cliente levanta la voz y afecta a otros. Describe cómo intervienes, qué dices, cuándo escalas y cómo cierras la situación.",
    ],
    psychometric: [
      "“¿Cómo te das cuenta cuando alguien necesita más apoyo o más libertad?”",
      "“Cuéntame de una persona que sabía hacer el trabajo, pero estaba desmotivada. ¿Qué hiciste?”",
      "“¿Cómo manejas a alguien que sí sabe trabajar, pero tiene mala actitud o genera conflicto?”",
      "“¿Qué haces si una persona está tratando pero no logra aprender o se queda atrás?”",
      "“En días de alta demanda, por ejemplo un sábado lleno, ¿tu forma de liderar cambia? ¿Cómo?”",
      "“¿Cómo convences a alguien del equipo de adoptar una nueva forma de trabajar o una nueva política?”",
      "“¿Cómo decides a quién delegar una tarea importante?”",
      "“¿Cómo das retroalimentación cuando alguien comete un error? ¿Cambias tu estilo según la persona?”",
      "“Cuéntame de la última vez que dos personas del equipo discutieron fuerte. ¿Qué hiciste tú para resolverlo?”",
      "“Describe cómo manejas a alguien que constantemente genera problemas, chismes o mala actitud.”",
      "“Si cocina y piso están peleando por tiempos o errores, ¿qué haces para que vuelvan a trabajar como equipo?”",
      "“¿Qué haces si ves que un conflicto está afectando el servicio en vivo?”",
      "“¿Cómo hablas con alguien que se pone a la defensiva cada vez que le das retroalimentación?”",
      "“Cuéntame de la situación más estresante que has vivido en el trabajo. ¿Qué pasó y cómo la manejaste tú personalmente?”",
      "“Cuando tienes muchos pendientes al mismo tiempo y todo urge, ¿cómo decides por dónde empezar?”",
      "“¿Qué haces cuando sientes que ya te estás saturando o poniendo de malas en medio del servicio?”",
      "“Describe un día en el que todo salió mal. ¿Cómo te organizaste para no perder el control?”",
      "“¿Qué haces para mantenerte enfocado cuando hay presión externa?”",
      "“¿Qué prefieres: libertad total o reglas claras? ¿Por qué?”",
      "“¿Qué tan cómodo te sientes tomando decisiones de dinero (descuentos/cortesías)?”",
      "“¿Qué haces si el dueño te pide algo que no te parece correcto?”",
      "“¿Cómo manejas la puntualidad y ausencias?”",
      "“¿Qué haces si un mesero llega tarde repetidamente?”",
      "“¿Cómo manejas favoritismos percibidos?”",
      "“¿Qué te molesta más en un equipo?”",
      "“¿Cómo motivas al equipo sin gritar?”",
      "“¿Cómo lidias con clientes difíciles?”",
      "“¿Qué haces si un cliente amenaza con mala reseña?”",
      "“¿Qué tan importante es el orden y limpieza para ti?”",
      "“¿Cómo reaccionas cuando te cambian el plan?”",
      "“¿Cómo te adaptas a cambios de menú y promociones?”",
      "“¿Qué haces si bar está retrasado?”",
      "“¿Qué haces si cocina está retrasada?”",
      "“¿Cómo mides el desempeño de un mesero?”",
      "“¿Cómo corriges errores sin humillar?”",
      "“¿Qué haces si un colaborador llora o se quiebra en servicio?”",
      "“¿Cómo manejas presión y multitarea?”",
      "“¿Qué haces si hay un accidente (vidrio roto, caída)?”",
      "“¿Cómo manejas seguridad del equipo?”",
      "“¿Qué harías si ves robo?”",
      "“¿Qué harías si alguien bebe alcohol en turno?”",
      "“¿Cómo administras tu energía en turnos largos?”",
      "“¿Qué haces cuando estás cansado pero debes liderar?”",
      "“¿Qué tan orientado eres a resultados?”",
      "“¿Qué harías si las ventas van bajas?”",
      "“¿Qué harías si hay exceso de quejas?”",
      "“¿Cómo te gusta recibir feedback?”",
      "“¿Qué harías si te corrigen frente a todos?”",
      "“¿Cómo manejas el conflicto con gerencia?”",
    ],
  },
  cook: {
    label: "Cocinero",
    practical: [
      "Describe cómo organizas tu mise en place antes del servicio para asegurar velocidad y consistencia.",
      "Explica cómo controlas temperaturas y evitas contaminación cruzada durante el servicio.",
      "Un platillo regresa por ‘salado’ o ‘crudo’. ¿Qué haces paso a paso y cómo previenes que vuelva a pasar?",
      "¿Cómo porcionas para mantener costos y consistencia? Describe tu método.",
      "Explica cómo priorizas comandas cuando entran muchas al mismo tiempo.",
      "¿Cómo trabajas con el pase/expediter para que salgan tiempos correctos?",
      "Describe tu rutina de cierre (limpieza, rotación, etiquetado, merma).",
      "¿Cómo reaccionas cuando falta un insumo clave a mitad de servicio?",
      "¿Qué haces si un compañero está atrasando la línea? ¿Cómo ayudas sin perder tu estación?",
      "Explica cómo asegurarías calidad constante en un día pico con alta presión.",
    ],
    psychometric: [
      "“¿Cómo manejas presión cuando la cocina está llena de comandas?”",
      "“¿Qué haces si te corrigen una receta enfrente de otros?”",
      "“¿Qué tan importante es seguir recetas al pie de la letra?”",
      "“¿Qué haces cuando te cambian el menú o un proceso?”",
      "“¿Cómo te organizas cuando tienes muchas tareas a la vez?”",
      "“¿Qué haces si un compañero no sigue higiene?”",
      "“¿Cómo reaccionas ante conflictos en cocina?”",
      "“¿Qué haces si hay gritos o estrés?”",
      "“¿Qué haces cuando estás cansado pero hay rush?”",
      "“¿Qué haces si un platillo sale mal?”",
      "“¿Cómo recibes retroalimentación?”",
      "“¿Qué tan disciplinado eres con limpieza?”",
      "“¿Qué haces si te piden trabajar más rápido?”",
      "“¿Qué haces si te equivocas?”",
      "“¿Qué haces si falta producto?”",
      "“¿Qué haces si un cliente se queja?”",
      "“¿Qué tan bien trabajas en equipo?”",
      "“¿Cómo manejas frustración?”",
      "“¿Qué harías si ves robo?”",
      "“¿Qué harías si alguien bebe en turno?”",
      "“¿Qué tan puntual eres?”",
      "“¿Cómo manejas cambios de turno?”",
      "“¿Cómo te adaptas a estándares?”",
      "“¿Qué te motiva en cocina?”",
      "“¿Qué te haría renunciar?”",
      "“¿Qué haces si no entiendes una instrucción?”",
      "“¿Qué haces si un líder te da una orden injusta?”",
      "“¿Cómo te mantienes enfocado?”",
      "“¿Cómo manejas multitarea?”",
      "“¿Qué haces cuando hay caos?”",
    ],
  },
  barman: {
    label: "Barman",
    practical: [
      "Describe tu mise en place ideal en barra (insumos, garnish, cristalería, estación) antes del servicio.",
      "Explica cómo harías 3 cócteles distintos simultáneamente sin perder calidad ni tiempos.",
      "Un cliente pide un cóctel ‘más dulce’ después de probarlo. ¿Qué haces y qué dices?",
      "¿Cómo controlas mermas y porcionado de destilados? Describe tu método.",
      "Explica cómo recomendarías bebidas para incrementar ticket sin presión.",
      "¿Cómo manejas una barra llena y pedidos de mesas al mismo tiempo? Prioridades y comunicación.",
      "Describe cómo limpias y cierras estación (higiene, herramientas, refrigeración, rotación).",
      "¿Qué haces si se acaba un destilado clave durante rush? Alternativas y comunicación.",
      "Explica cómo estandarizas recetas y te aseguras que otros bartenders hagan lo mismo.",
      "Un cliente molesto por demora/incorrecto. ¿Cómo lo resuelves manteniendo experiencia?",
    ],
    psychometric: [
      "“¿Cómo manejas presión con muchos tickets?”",
      "“¿Qué haces si te cambian la receta?”",
      "“¿Qué tan cómodo eres vendiendo?”",
      "“¿Cómo manejas clientes difíciles o insistentes?”",
      "“¿Cómo recibes correcciones?”",
      "“¿Qué haces si te equivocas en un cóctel?”",
      "“¿Qué haces si un compañero está lento?”",
      "“¿Qué haces si falta insumo?”",
      "“¿Qué tan disciplinado eres con limpieza?”",
      "“¿Qué haces si te piden trabajar más rápido?”",
      "“¿Qué haces cuando estás cansado?”",
      "“¿Cómo trabajas en equipo con meseros?”",
      "“¿Cómo manejas conflicto con cocina/piso?”",
      "“¿Qué te molesta más en un equipo?”",
      "“¿Qué harías si ves robo?”",
      "“¿Qué harías si alguien bebe en turno?”",
      "“¿Qué tan puntual eres?”",
      "“¿Cómo manejas estrés fuera del trabajo?”",
      "“¿Qué te motiva en barra?”",
      "“¿Qué te haría renunciar?”",
    ],
  },
  chef_manager: {
    label: "Chef gerente",
    practical: [
      "¿Imagina que entra una persona totalmente nueva al equipo, nunca ha trabajado en restaurante. ¿Cómo sería tu forma de dirigirla en sus primeros días? (explica tu estilo, pasos y supervisión).",
      "“Y cuando alguien ya tiene experiencia, domina su puesto… ¿cómo cambia tu manera de liderarlo?”",
      "“¿Cómo te das cuenta cuando alguien necesita más apoyo o más libertad?”",
      "“Cuéntame de una persona que sabía hacer el trabajo, pero estaba desmotivada. ¿Qué hiciste?”",
      "“¿Cómo manejas a alguien que sí sabe trabajar, pero tiene mala actitud o genera conflicto?”",
      "“¿Qué haces si una persona está tratando pero no logra aprender o se queda atrás?”",
      "“En días de alta demanda, por ejemplo un sábado lleno, ¿tu forma de liderar cambia? ¿Cómo?”",
      "“¿Cómo convences a alguien del equipo de adoptar una nueva forma de trabajar o una nueva política?”",
      "“¿Cómo decides a quién delegar una tarea importante?”",
      "“¿Cómo das retroalimentación cuando alguien comete un error? ¿Cambias tu estilo según la persona?”",
      "“Cuéntame de la última vez que dos personas del equipo discutieron fuerte. ¿Qué hiciste tú para resolverlo?”",
      "“Describe cómo manejas a alguien que constantemente genera problemas, chismes o mala actitud.”",
      "“Si cocina y piso están peleando por tiempos o errores, ¿qué haces para que vuelvan a trabajar como equipo?”",
      "“¿Qué haces si ves que un conflicto está afectando el servicio en vivo?”",
      "“¿Cómo hablas con alguien que se pone a la defensiva cada vez que le das retroalimentación?”",
      "“Cuéntame de la situación más estresante que has vivido en el trabajo. ¿Qué pasó y cómo la manejaste tú personalmente?”",
      "“Cuando tienes muchos pendientes al mismo tiempo y todo urge, ¿cómo decides por dónde empezar?”",
      "“¿Qué haces cuando sientes que ya te estás saturando o poniendo de malas en medio del servicio?”",
      "“Describe un día en el que todo salió mal (clientes, equipo, proveedores). ¿Cómo te organizaste para no perder el control?”",
      "“¿Qué haces para mantenerte enfocado cuando hay presión externa (dueño, clientes, fallas, etc.)?”",
      /* Este práctico tiene muchas más preguntas (tu PDF trae ~99). 
         Si quieres que lo deje completo en el banco también, lo hago, pero aquí te dejo el bloque inicial para que funcione ya.
         (Si quieres, te lo pego completo en el siguiente mensaje). */
    ],
    psychometric: [
      "¿Qué tan cómodo te sientes tomando decisiones bajo presión?",
      "¿Cómo manejas la frustración cuando alguien no cumple?",
      "¿Cómo reaccionas cuando te corrigen en público?",
      "¿Qué haces cuando hay conflictos constantes en el equipo?",
      "¿Cómo manejas estrés y multitarea en servicios pico?",
      "¿Qué tan importante es para ti el orden y disciplina?",
      "¿Qué haces si un líder intermedio falla frente al equipo?",
      "¿Cómo detectas talento y lo desarrollas?",
      "¿Cómo manejas percepción de favoritismos?",
      "¿Qué haces si alguien no respeta estándares de inocuidad?",
      /* Igual: tu psicométrico de chef trae muchas más (~64). Si quieres, lo dejo completo. */
    ],
  },
};
